### PR TITLE
Temporary patch for #9, plus made a README

### PR DESCRIPTION
**Pull request by xbony2**

### CODE REVIEW

**Comment by xbony2** [comment]
Tested with making the CPC tilesheet. However this is with the current TIlesheets version, 4.3.0. I don't know if it will work with 5.0, but in any case, that will probably require an update to mediawiki-rs first.

**Comment by xbony2** [comment]
Actually based on [this](https://github.com/FTB-Gamepedia/Tilesheets/blob/master/api/TilesheetsAddTilesApi.php#L43) I think we'll just need to change [this](https://github.com/FTB-Gamepedia/ftb-rs/blob/master/src/tilesheets.rs#L336). I'll do that once the tilesheet extension on the wiki is updated so I can test it.

**Comment by xbony2** [comment]
This PR is made irrelevant by #11, however the fork is mildly useful while the extension has not been updated yet.

**Comment by retep998** [comment]
Closing as #11 was merged.

**Pull request closed without merging**
